import Head from "next/head";
import { Suspense } from "react";
import styles from "../styles/Home.module.css";

import dynamic from "next/dynamic";

const List = dynamic(() => import("../src/components/List"), {
  loading: () => <div>...loading</div>,
  ssr: false,
});

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Suspense fallback={<div>...loading</div>}>
          <List />
        </Suspense>
      </main>
    </div>
  );
};

export default Home;
